import {PlaceResponseDTO} from './place'
import {PostResponseDTO} from './post'
import {RegionResponseDTO} from './region'
import {UserResponseDTO} from './user'

export interface DiaryDetailDTO {
  id: number
  title: string
  content: string
  keywords: string
  posts: PostResponseDTO[]
  createdBy: UserResponseDTO
  createdAt: string // ISO datetime string format
  modifiedBy: UserResponseDTO
  modifiedAt: string // ISO datetime string format
  isAutoGenerated: boolean
  regions: RegionResponseDTO[]
}

export interface DiaryRequestDTO {
  title: string
  content: string
  keywords: string
  isAutoGenerated: boolean
  postIds: number[]
}

export interface DiaryResponseDTO {
  id: number
  title: string
  content: string
  keywords: string
  isAutoGenerated: boolean
  createdBy: string // From BaseDTO
  createdAt: string // From BaseDTO
  updatedBy: string // From BaseDTO
  updatedAt: string // From BaseDTO
}
