export interface DiaryResponseDTO {
  id: number;
  title: string;
  content: string;
  date: string; // LocalDateTime as ISO string
  albumId: number;
  region: string;
  keywords: string;
  isAutoGenerated: boolean;
  createdBy: string;
  createdAt: string;
}

export interface DiaryDetailDTO extends DiaryResponseDTO {
  posts: {
    id: number;
    title: string;
    content: string;
    createdAt: string;
    updatedAt: string;
  }[];
}

export interface DiaryRequestDTO {
  title: string;
  content: string;
  region: string;
  date: string; // LocalDate as string
  keywords: string;
  isAutoGenerated: boolean;
  postIds: number[];
}